-- MySQL Script generated by MySQL Workbench
-- Sun Oct 27 21:06:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role` ;

CREATE TABLE IF NOT EXISTS `role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT 'Role name (can be Administrator, Visitor etc...)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Primary Key ID',
  `role_id` INT NULL,
  `id_discord_account` VARCHAR(255) NULL COMMENT 'Discord Account Unique ID',
  `id_jellyfin_account` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `username` VARCHAR(255) NOT NULL COMMENT 'Username used on target app',
  `password` VARCHAR(255) NULL COMMENT 'secret password to authenticate user\nnull means the account hasn\'t been activated',
  `created_at` DATETIME NOT NULL DEFAULT NOW() COMMENT 'User created at\n',
  `updated_at` DATETIME NOT NULL DEFAULT NOW() COMMENT 'Updated at',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idDiscordAccount_UNIQUE` (`id_discord_account` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `id_jellyfin_account_UNIQUE` (`id_jellyfin_account` ASC),
  INDEX `fk_user_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_connections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_connections` ;

CREATE TABLE IF NOT EXISTS `user_connections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `connection_at` DATETIME NOT NULL DEFAULT NOW() COMMENT 'Connection made at',
  `connection_ip` VARCHAR(45) NOT NULL COMMENT 'IP used for the login process',
  `location` VARCHAR(255) NULL COMMENT 'From where the user has been logged',
  `device_type` VARCHAR(50) NULL COMMENT 'Device Type used for the login (example : Smartphone, PC, MacOs, Tablet..)',
  `browser_info` VARCHAR(255) NULL COMMENT 'Browser information (Firefox, Chrome, IE..)',
  `operating_system` VARCHAR(255) NULL COMMENT 'Linux, Windows, MacOS..\n',
  `user_agent` VARCHAR(255) NULL COMMENT 'User Agent in HTTP Request',
  INDEX `fk_UserConnections_Users1_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_UserConnections_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `role`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `role` (`id`, `name`) VALUES (1, 'VIEWER');
INSERT INTO `role` (`id`, `name`) VALUES (2, 'ADMIN');
INSERT INTO `role` (`id`, `name`) VALUES (3, 'DISABLED');

COMMIT;

