name: Docker Build Image

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - dev
      - main

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t streamzer.bot .